# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables for Python unbuffered output and optimizations
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        gettext \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Install Python dependencies
COPY req.txt /app/
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Copy the Django project files into the container
COPY . /app/

# Collect static files (if needed)
RUN python manage.py collectstatic --no-input

# Start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
